#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EWCAndroid.Resource", IsApplication=true)]

namespace EWCAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circleColor = global::EWCAndroid.Resource.Attribute.circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circularProgressBarStyle = global::EWCAndroid.Resource.Attribute.circularProgressBarStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_gravity = global::EWCAndroid.Resource.Attribute.circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate = global::EWCAndroid.Resource.Attribute.circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate_interval = global::EWCAndroid.Resource.Attribute.circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_marker_progress = global::EWCAndroid.Resource.Attribute.circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress = global::EWCAndroid.Resource.Attribute.circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_background_color = global::EWCAndroid.Resource.Attribute.circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_color = global::EWCAndroid.Resource.Attribute.circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_stroke_width = global::EWCAndroid.Resource.Attribute.circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate = global::EWCAndroid.Resource.Attribute.indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate_interval = global::EWCAndroid.Resource.Attribute.indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.innerSize = global::EWCAndroid.Resource.Attribute.innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.max = global::EWCAndroid.Resource.Attribute.max;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinned = global::EWCAndroid.Resource.Attribute.pinned;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinnedDrawable = global::EWCAndroid.Resource.Attribute.pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progress = global::EWCAndroid.Resource.Attribute.progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressButtonStyle = global::EWCAndroid.Resource.Attribute.progressButtonStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressColor = global::EWCAndroid.Resource.Attribute.progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.shadowDrawable = global::EWCAndroid.Resource.Attribute.shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.unpinnedDrawable = global::EWCAndroid.Resource.Attribute.unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_circle_color = global::EWCAndroid.Resource.Color.progress_default_circle_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_progress_color = global::EWCAndroid.Resource.Color.progress_default_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_dark = global::EWCAndroid.Resource.Color.refractored_background_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_dark = global::EWCAndroid.Resource.Color.refractored_background_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_light = global::EWCAndroid.Resource.Color.refractored_background_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_light = global::EWCAndroid.Resource.Color.refractored_background_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark = global::EWCAndroid.Resource.Color.refractored_bright_foreground_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark_disabled = global::EWCAndroid.Resource.Color.refractored_bright_foreground_dark_disabled;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_dark = global::EWCAndroid.Resource.Color.refractored_bright_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_light = global::EWCAndroid.Resource.Color.refractored_bright_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_dark = global::EWCAndroid.Resource.Color.refractored_bright_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_light = global::EWCAndroid.Resource.Color.refractored_bright_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_light = global::EWCAndroid.Resource.Color.refractored_bright_foreground_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_dark = global::EWCAndroid.Resource.Color.refractored_dim_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_light = global::EWCAndroid.Resource.Color.refractored_dim_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_dark = global::EWCAndroid.Resource.Color.refractored_dim_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_light = global::EWCAndroid.Resource.Color.refractored_dim_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_dark = global::EWCAndroid.Resource.Color.refractored_highlighted_text_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_light = global::EWCAndroid.Resource.Color.refractored_highlighted_text_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_dark = global::EWCAndroid.Resource.Color.refractored_hint_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_light = global::EWCAndroid.Resource.Color.refractored_hint_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_bright = global::EWCAndroid.Resource.Color.refractored_holo_blue_bright;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_dark = global::EWCAndroid.Resource.Color.refractored_holo_blue_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_light = global::EWCAndroid.Resource.Color.refractored_holo_blue_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_dark = global::EWCAndroid.Resource.Color.refractored_holo_green_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_light = global::EWCAndroid.Resource.Color.refractored_holo_green_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_dark = global::EWCAndroid.Resource.Color.refractored_holo_orange_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_light = global::EWCAndroid.Resource.Color.refractored_holo_orange_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_purple = global::EWCAndroid.Resource.Color.refractored_holo_purple;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_dark = global::EWCAndroid.Resource.Color.refractored_holo_red_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_light = global::EWCAndroid.Resource.Color.refractored_holo_red_light;
			global::com.refractored.monodroidtoolkit.Resource.Dimension.progress_inner_size = global::EWCAndroid.Resource.Dimension.progress_inner_size;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_pinned = global::EWCAndroid.Resource.Drawable.pin_progress_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_shadow = global::EWCAndroid.Resource.Drawable.pin_progress_shadow;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_unpinned = global::EWCAndroid.Resource.Drawable.pin_progress_unpinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_normal_holo = global::EWCAndroid.Resource.Drawable.scrubber_control_normal_holo;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_pressed_holo = global::EWCAndroid.Resource.Drawable.scrubber_control_pressed_holo;
			global::com.refractored.monodroidtoolkit.Resource.Id.bottom = global::EWCAndroid.Resource.Id.bottom;
			global::com.refractored.monodroidtoolkit.Resource.Id.center = global::EWCAndroid.Resource.Id.center;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_horizontal = global::EWCAndroid.Resource.Id.center_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_vertical = global::EWCAndroid.Resource.Id.center_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip = global::EWCAndroid.Resource.Id.clip;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_horizontal = global::EWCAndroid.Resource.Id.clip_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_vertical = global::EWCAndroid.Resource.Id.clip_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.end = global::EWCAndroid.Resource.Id.end;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill = global::EWCAndroid.Resource.Id.fill;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_horizontal = global::EWCAndroid.Resource.Id.fill_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_vertical = global::EWCAndroid.Resource.Id.fill_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.left = global::EWCAndroid.Resource.Id.left;
			global::com.refractored.monodroidtoolkit.Resource.Id.right = global::EWCAndroid.Resource.Id.right;
			global::com.refractored.monodroidtoolkit.Resource.Id.start = global::EWCAndroid.Resource.Id.start;
			global::com.refractored.monodroidtoolkit.Resource.Id.top = global::EWCAndroid.Resource.Id.top;
			global::com.refractored.monodroidtoolkit.Resource.Integer.circular_indeterminent_interval = global::EWCAndroid.Resource.Integer.circular_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Integer.progressbutton_indeterminent_interval = global::EWCAndroid.Resource.Integer.progressbutton_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBar = global::EWCAndroid.Resource.Style.CircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBarLight = global::EWCAndroid.Resource.Style.CircularProgressBarLight;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton = global::EWCAndroid.Resource.Style.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton_Pin = global::EWCAndroid.Resource.Style.ProgressButton_Pin;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_gravity = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar_circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar_circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_color = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar_circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width = global::EWCAndroid.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton = global::EWCAndroid.Resource.Styleable.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_clickable = global::EWCAndroid.Resource.Styleable.ProgressButton_android_clickable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_focusable = global::EWCAndroid.Resource.Styleable.ProgressButton_android_focusable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_selectableItemBackground = global::EWCAndroid.Resource.Styleable.ProgressButton_android_selectableItemBackground;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_circleColor = global::EWCAndroid.Resource.Styleable.ProgressButton_circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate = global::EWCAndroid.Resource.Styleable.ProgressButton_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate_interval = global::EWCAndroid.Resource.Styleable.ProgressButton_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_innerSize = global::EWCAndroid.Resource.Styleable.ProgressButton_innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_max = global::EWCAndroid.Resource.Styleable.ProgressButton_max;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinned = global::EWCAndroid.Resource.Styleable.ProgressButton_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinnedDrawable = global::EWCAndroid.Resource.Styleable.ProgressButton_pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progress = global::EWCAndroid.Resource.Styleable.ProgressButton_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progressColor = global::EWCAndroid.Resource.Styleable.ProgressButton_progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_shadowDrawable = global::EWCAndroid.Resource.Styleable.ProgressButton_shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_unpinnedDrawable = global::EWCAndroid.Resource.Styleable.ProgressButton_unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme = global::EWCAndroid.Resource.Styleable.Theme;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme_circularProgressBarStyle = global::EWCAndroid.Resource.Styleable.Theme_circularProgressBarStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int circleColor = 2130771971;
			
			// aapt resource value: 0x7f010014
			public const int circularProgressBarStyle = 2130771988;
			
			// aapt resource value: 0x7f01000c
			public const int circular_gravity = 2130771980;
			
			// aapt resource value: 0x7f010012
			public const int circular_indeterminate = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int circular_indeterminate_interval = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int circular_marker_progress = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int circular_progress = 2130771982;
			
			// aapt resource value: 0x7f010011
			public const int circular_progress_background_color = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int circular_progress_color = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int circular_stroke_width = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int indeterminate = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int indeterminate_interval = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int innerSize = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int max = 2130771970;
			
			// aapt resource value: 0x7f010009
			public const int pinned = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int pinnedDrawable = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int progress = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int progressButtonStyle = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int progressColor = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int shadowDrawable = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int unpinnedDrawable = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int progress_default_circle_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int progress_default_progress_color = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int refractored_background_dark = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int refractored_background_holo_dark = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int refractored_background_holo_light = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int refractored_background_light = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int refractored_bright_foreground_dark = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int refractored_bright_foreground_dark_disabled = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int refractored_bright_foreground_disabled_holo_dark = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int refractored_bright_foreground_disabled_holo_light = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int refractored_bright_foreground_holo_dark = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int refractored_bright_foreground_holo_light = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int refractored_bright_foreground_light = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int refractored_dim_foreground_disabled_holo_dark = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int refractored_dim_foreground_disabled_holo_light = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int refractored_dim_foreground_holo_dark = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int refractored_dim_foreground_holo_light = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int refractored_highlighted_text_holo_dark = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int refractored_highlighted_text_holo_light = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int refractored_hint_foreground_holo_dark = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int refractored_hint_foreground_holo_light = 2131034130;
			
			// aapt resource value: 0x7f05001e
			public const int refractored_holo_blue_bright = 2131034142;
			
			// aapt resource value: 0x7f050018
			public const int refractored_holo_blue_dark = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int refractored_holo_blue_light = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int refractored_holo_green_dark = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int refractored_holo_green_light = 2131034134;
			
			// aapt resource value: 0x7f05001d
			public const int refractored_holo_orange_dark = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int refractored_holo_orange_light = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int refractored_holo_purple = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int refractored_holo_red_dark = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int refractored_holo_red_light = 2131034135;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int progress_inner_size = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppIcon291x = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AppIcon292x = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AppIcon293x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AppIcon50x50 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BackgroundRedGirl = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int backgroundwaxing = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int facebook = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int goggleLogin = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mainfaqRed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int mainlocRed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mainptsRed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pin_progress_pinned = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pin_progress_shadow = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pin_progress_unpinned = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int res1x = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int scrubber_control_normal_holo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int scrubber_control_pressed_holo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int twitterLogin = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int bottom = 2131361792;
			
			// aapt resource value: 0x7f0a0023
			public const int bottomLayout = 2131361827;
			
			// aapt resource value: 0x7f0a0016
			public const int btnCreateAccount = 2131361814;
			
			// aapt resource value: 0x7f0a0018
			public const int btnFacebook = 2131361816;
			
			// aapt resource value: 0x7f0a001a
			public const int btnGoogle = 2131361818;
			
			// aapt resource value: 0x7f0a001c
			public const int btnLogIn = 2131361820;
			
			// aapt resource value: 0x7f0a0020
			public const int btnNewPassword = 2131361824;
			
			// aapt resource value: 0x7f0a0019
			public const int btnTwitter = 2131361817;
			
			// aapt resource value: 0x7f0a0001
			public const int center = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int center_horizontal = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int center_vertical = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int clip = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int clip_horizontal = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int clip_vertical = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int end = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int fill = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int fill_horizontal = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int fill_vertical = 2131361802;
			
			// aapt resource value: 0x7f0a000f
			public const int imgCreateAccountScreen = 2131361807;
			
			// aapt resource value: 0x7f0a002a
			public const int imgFAQs = 2131361834;
			
			// aapt resource value: 0x7f0a001e
			public const int imgForgotPasswordScreen = 2131361822;
			
			// aapt resource value: 0x7f0a0026
			public const int imgLocator = 2131361830;
			
			// aapt resource value: 0x7f0a0021
			public const int imgLoginScreen = 2131361825;
			
			// aapt resource value: 0x7f0a001d
			public const int imgLogo = 2131361821;
			
			// aapt resource value: 0x7f0a0028
			public const int imgPoints = 2131361832;
			
			// aapt resource value: 0x7f0a0024
			public const int imgReservations = 2131361828;
			
			// aapt resource value: 0x7f0a001b
			public const int imgScreen = 2131361819;
			
			// aapt resource value: 0x7f0a0022
			public const int lblForgotPassword = 2131361826;
			
			// aapt resource value: 0x7f0a0017
			public const int lblSignUpWith = 2131361815;
			
			// aapt resource value: 0x7f0a000b
			public const int left = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int right = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int start = 2131361805;
			
			// aapt resource value: 0x7f0a002e
			public const int textView1 = 2131361838;
			
			// aapt resource value: 0x7f0a0014
			public const int toggleButton1 = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int toggleButton2 = 2131361813;
			
			// aapt resource value: 0x7f0a000e
			public const int top = 2131361806;
			
			// aapt resource value: 0x7f0a002c
			public const int topLayout = 2131361836;
			
			// aapt resource value: 0x7f0a0012
			public const int txtEmail = 2131361810;
			
			// aapt resource value: 0x7f0a002b
			public const int txtFAQs = 2131361835;
			
			// aapt resource value: 0x7f0a002d
			public const int txtFeedBack = 2131361837;
			
			// aapt resource value: 0x7f0a001f
			public const int txtForgotPasswordEmail = 2131361823;
			
			// aapt resource value: 0x7f0a0010
			public const int txtFullName = 2131361808;
			
			// aapt resource value: 0x7f0a0027
			public const int txtLocator = 2131361831;
			
			// aapt resource value: 0x7f0a0013
			public const int txtPassword = 2131361811;
			
			// aapt resource value: 0x7f0a0011
			public const int txtPhoneNumber = 2131361809;
			
			// aapt resource value: 0x7f0a0029
			public const int txtPoints = 2131361833;
			
			// aapt resource value: 0x7f0a0025
			public const int txtReservations = 2131361829;
			
			// aapt resource value: 0x7f0a002f
			public const int txtShare = 2131361839;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070001
			public const int circular_indeterminent_interval = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int progressbutton_indeterminent_interval = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CreateAccountScreen = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FirstScreen = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ForgotPassword = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LoginScreen = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int AppIcon291x = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AppIcon292x = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BackgroundRedGirl = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BackgroundRedGirl3x = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Icon = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login2x = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Login3x = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Login750 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LoginImage01 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int mainfaqRed = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int mainlocRed = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int mainptsRed = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int res1x = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int res2x = 2130903054;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int hello = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int name = 2131296258;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int CircularProgressBar = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CircularProgressBarLight = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int ProgressButton = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ProgressButton_Pin = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int Theme_Splash = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HoloCircularProgressBar = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] ProgressButton = new int[] {
					16842970,
					16842981,
					16843534,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public const int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public const int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public const int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public const int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public const int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public const int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public const int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public const int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public const int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public const int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public const int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public const int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public const int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] Theme = new int[] {
					2130771988};
			
			// aapt resource value: 0
			public const int Theme_circularProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
