#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EWCAndroid.Resource", IsApplication=true)]

namespace EWCAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::EWCAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int _DS_Store = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AppIcon291x = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AppIcon292x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AppIcon293x = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int AppIcon50x50 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int arrowright = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BackgroundRedGirl = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int backgroundwaxing = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int facebook = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int FAQNewGray1x = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int GiftGorgeous1x = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int goggleLogin = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int HamburgerIconWhite1x = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int LocationNewGray1x = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mainCal1x = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int mainfaq1x = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int mainfaqRed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int mainlocRed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int mainpts1x = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int mainptsRed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int RedWaxRing = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int res1x = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sharetheappx = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int struz1x = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int twitterLogin = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int bottomLayout = 2131165204;
			
			// aapt resource value: 0x7f070007
			public const int btnCreateAccount = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int btnFacebook = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int btnGoogle = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int btnLogIn = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int btnNewPassword = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int btnTwitter = 2131165194;
			
			// aapt resource value: 0x7f070015
			public const int imageView1 = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int imageView2 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int imageView3 = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int imageView4 = 2131165211;
			
			// aapt resource value: 0x7f070000
			public const int imgCreateAccountScreen = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int imgForgotPasswordScreen = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int imgLoginScreen = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int imgLogo = 2131165198;
			
			// aapt resource value: 0x7f07001a
			public const int imgMenu = 2131165210;
			
			// aapt resource value: 0x7f07000c
			public const int imgScreen = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int lblForgotPassword = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int lblSignUpWith = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int segBeenThere = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int segGender = 2131165190;
			
			// aapt resource value: 0x7f070016
			public const int textView1 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int topLayout = 2131165207;
			
			// aapt resource value: 0x7f070003
			public const int txtEmail = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int txtForgotPasswordEmail = 2131165200;
			
			// aapt resource value: 0x7f070001
			public const int txtFullName = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int txtPassword = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int txtPhoneNumber = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CreateAccountScreen = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FirstScreen = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ForgotPassword = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LoginScreen = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int MenuListScreen = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int SplashScreen = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int AppIcon291x = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AppIcon292x = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BackgroundRedGirl = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BackgroundRedGirl3x = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Icon = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login2x = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Login3x = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Login750 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LoginImage01 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int mainfaqRed = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int mainlocRed = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int mainptsRed = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int res1x = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int res2x = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int res3x = 2130903055;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int mainTitleFeedback = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int mainTitleShare = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int mainTitleSurprise = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
